language: c++
compiler: clang
os: linux
sudo: required

matrix:
    include:
        # Clang 3.6
        - env: UNIT_TESTS=true COMPILER=clang++-3.6 CMAKE_OPTIONS="-DVRM_PP_ENABLE_MEMCHECK=ON"
          addons: 
            apt:
                sources:
                    - ubuntu-toolchain-r-test
                    - llvm-toolchain-precise
                    - llvm-toolchain-precise-3.6
                packages:
                    - clang-3.6
                    - valgrind

        # Clang 3.7
        - env: UNIT_TESTS=true COMPILER=clang++-3.7 CMAKE_OPTIONS="-DVRM_PP_ENABLE_MEMCHECK=ON"
          addons: 
            apt:
                sources:
                    - ubuntu-toolchain-r-test
                    - llvm-toolchain-precise
                    - llvm-toolchain-precise-3.7
                packages:
                    - clang-3.7
                    - valgrind

        # Gcc 4.9
        - env: UNIT_TESTS=true COMPILER=g++-4.9 CMAKE_OPTIONS="-DVRM_PP_ENABLE_MEMCHECK=ON"
          addons:
            apt:
                sources:
                    - ubuntu-toolchain-r-test
                    - llvm-toolchain-precise
                    - llvm-toolchain-precise-3.7
                packages:
                    - gcc-4.9
                    - g++-4.9
                    - valgrind

        # Gcc 5.1
        - env: UNIT_TESTS=true COMPILER=g++-5 CMAKE_OPTIONS="-DVRM_PP_ENABLE_MEMCHECK=ON"
          addons:
            apt:
                sources:
                    - ubuntu-toolchain-r-test
                    - llvm-toolchain-precise
                    - llvm-toolchain-precise-3.7
                packages:
                    - gcc-5
                    - g++-5
                    - valgrind

before_install:
    - sudo apt-get install software-properties-common
    - sudo add-apt-repository ppa:george-edison55/cmake-3.x
    - sudo apt-get update
    - sudo apt-get install cmake

install:
    # Set and create dependencies directory
    - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
    - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}

before_script:
    - cd ${TRAVIS_BUILD_DIR}
    - ./init-repository.sh
    - mkdir build && cd build
    - cmake .. -DCMAKE_CXX_COMPILER=${COMPILER} -DVRM_PP_ENABLE_WERROR=ON ${CMAKE_OPTIONS}

script:
    - cd ${TRAVIS_BUILD_DIR}
    - cd build
    - make -j