language: c++

compiler:
    - gcc
    - clang

os: linux
sudo: false

install: true

before_script:
    - cd ${TRAVIS_BUILD_DIR}
    - mkdir build && cd build
    - cmake .. -DCMAKE_CXX_COMPILER=${COMPILER} -DVRM_PP_ENABLE_WERROR=ON ${CMAKE_OPTIONS}

script: 
    - cd ${TRAVIS_BUILD_DIR}
    - cd build
    - make -j